### PR TITLE
feat: adds section to device info for certificate information and allows for downloading of certs

### PR DESCRIPTION
**Pull request by Craig-Spencer-12**
## PR Checklist

- [ ] Unit Tests have been added for new changes
- [ ] API tests have been updated if applicable
- [ ] All commented code has been removed
- [ ] If you've added a dependency, you've ensured license is compatible with Apache 2.0 and clearly outlined the added dependency.

### CODE REVIEW

**Comment by Craig-Spencer-12** [comment]
Web ui should look like this with the automatic TLS cert and one wifi configuration 
image

**Comment by Craig-Spencer-12** [comment]
Some choices that might need to be changed include:

1. ID for key is the first 10 chars of the key
2. ID for a cert without a common name is the first 10 chars of the cert
3. File extensions for downloads are .pem for certs and .pub for keys

**Review by rsdmike — DISMISSED** [review]
https://rsd-intel.slack.com/archives/C010XA13G76/p1724691939386519?thread_ts=1724689804.551239&cid=C010XA13G76

**Review by rsdmike — APPROVED** [review]

**Review by madhavilosetty-intel — APPROVED** [review]

**Pull request merged**
