### PR TITLE
feat: support Alarm Service APIs

### PR DESCRIPTION
**Pull request by orinem**
## PR Checklist

- [ ] Unit Tests have been added for new changes
- [ ] API tests have been updated if applicable
- [X] All commented code has been removed
- [X] If you've added a dependency, you've ensured license is compatible with Apache 2.0 and clearly outlined the added dependency.

## What are you changing?

Adding simple UI to display, delete and add alarm occurrences.

## Anything the reviewer should know when reviewing this PR?

It's about as simple as it gets.  It displays existing alarms in the device details page.  The trash cans delete alarms.  Fill in fields below the list of existing alarms and click "+Add New" to add an alarm.  It would have been better to overlay a separate page to add an alarm and someone more skilled with angular than me is welcome to do it.

Alarms times are rounded down to the nearest minute (AMT doesn't allow finer resolution).  Similarly, intervals for periodic alarms are set in minutes.

Alarm names should be at most 32 characters and should be unique as the InstanceID will be set to the same as the alarm name.

Local time will be converted to, and passed to AMT as UTC.

Screenshot for the record:

image

### If the there are associated PRs in other repositories, please link them here (i.e. open-amt-cloud-toolkit/repo#365 )

mps: https://github.com/open-amt-cloud-toolkit/mps/pull/658
wsman-messages: https://github.com/open-amt-cloud-toolkit/wsman-messages/pull/180

The start time field for adding an alarm uses the following package which has an MIT license:

```@angular-material-components/datetime-picker```

### CODE REVIEW

**Review by matt-primrose — APPROVED** [review]
Testing on my AMT 15 machine, working well!

**Comment by orinem** [comment]
@matt-primrose oops - not my intent to dismiss anything.

I added the test I had locally for getAlarmOccurrences and the package-lock.json for date-time-picker.

**Comment by matt-primrose** [comment]
@orinem no problem.  Can you address some of the testing gaps in code coverage for the new alarm capabilities?

**Comment by orinem** [comment]
@matt-primrose tests for adding/deleting alarms are on my to-do list!

**Comment by orinem** [comment]
Tests for adding/deleting alarms have been added.  The full page reload and window.confirm calls were faked for the tests for now.  Ideally just the alarms part of the page needs reloading after adding or deleting an alarm.

**Review by matt-primrose — APPROVED** [review]

**Pull request merged**
